### ISSUE TITLE
[Elastic Agent] Handover the trust information of Kibana to the endpoint.

### ISSUE THREAD

**Issue by ph** [elastic/elastic-agent-client#11]
Endpoint will require to receive information about how to connect to Kibana from the Elastic-Agent, including list of URLs, ca_pins and possibly certificates.

We could possibly add this to the `ConnInfo` struct ?

https://github.com/elastic/elastic-agent-client/blob/d6a9eb4f6d072cf646997e2b8cedb2801069dc40/elastic-agent-client.proto#L15-L28

The use case for this is to reach a Kibana API to download artifacts for the endpoint.

**Comment by ph** [comment]
@blakerouse I believe we can close this?

**Comment by blakerouse** [comment]
Yes it can be closed.
