### ISSUE TITLE
[Elastic Agent] Review the contract between the Agent and process

### ISSUE THREAD

**Issue by ph** [elastic/elastic-agent-client#12]
Review the [contract](https://github.com/elastic/elastic-agent-client/blob/master/elastic-agent-client.proto) in the context of Endpoint.

Also this [proposal](https://github.com/elastic/elastic-agent-client/issues/11#issuecomment-642180178) to pass Kibana information to the  running process

**Comment by gogochan** [comment]
The proposal looks good. So the consensus is that the initial connection isn't to pass `Kibana` information, but the `Agent Connection` information.

To reiterate, an Endpoint would make an initial connection to the Agent to retrieve this `ConnInfo`. The Endpoint disconnects itself and uses the `CA cert`, `key`, and `cert` to make a secured connection to the Agent.

I'm running a quick compilation check with the contract to ensure we have no naming collision or issue.

**Comment by gogochan** [comment]
a Quick compilation validation passes. I think we are good to go.

**Comment by ph** [comment]
Just to clarify the initial connection, the connection would be done to another port over TCP, on connect we will you the details.

I am going to close this as resolved.
