### ISSUE TITLE
Elastic agent doesn't respect config file parameters

### ISSUE THREAD

**Issue by munavirch** [elastic/elastic-agent-client#28]
Elastic agent doesn't seem to respect the parameters specified in the config file. As per below config, gRPC should bind to 6790. Rather it binds on 6789 (default).

    agent.grpc:
      address: localhost
      port: 6790

Here's the open ports for ES agent after running it.

    [elastic-agent.exe]
    TCP    127.0.0.1:6789         127.0.0.1:53942        ESTABLISHED     27460
    [elastic-agent.exe]
    TCP    127.0.0.1:6789         127.0.0.1:53945        ESTABLISHED     27460
    [elastic-agent.exe]
    TCP    127.0.0.1:6789         127.0.0.1:53954        ESTABLISHED     27460
    [elastic-agent.exe]
    TCP    127.0.0.1:6789         127.0.0.1:63411        ESTABLISHED     27460

**Comment by narph** [comment]
hi @munavirch , https://github.com/elastic/beats/pull/29297 should fix this issue, meanwhile, if you add the:
```
agent.grpc:
  address: localhost
  port: 6790
```

inside `fleet.yml` , things should work. Let us know if they don't.
