### ISSUE TITLE
Should we differntiate between V2 Unit states?

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent-client#44]
So, a footcannon that I've shot myself with a few times is mixing up what Unit states will be sent to the client via the server, and what unit states are purely for a client to report status:

https://github.com/elastic/elastic-agent-client/blob/3e014f7c0e838727f2596e3463f5110590e529cf/pkg/proto/elastic-agent-client.pb.go#L94-L102

For example, `State_STOPPING` will only ever be sent by a client to the server to update its status, but there's nothing in the code to suggest this, and so it's easy to treat it like a state that will be requested by `Expected`, leading to coding errors.

I wonder if the code in `unit.go` should break out the states into multiple types, for example a `UnitStateExpected` and a `UnitStateReported` just do make this distinction clear at a type level. Cc @cmacknz

**Comment by cmacknz** [comment]
I tried to address this with documentation of the unit states https://github.com/elastic/elastic-agent-client/pull/45

I agree this needs to be clarified, I've seen this confusion in the unit/beat PRs as well.

**Comment by cmacknz** [comment]
Closing this, this is now explicitly documented in the proto file: https://github.com/elastic/elastic-agent-client/pull/45
