### ISSUE TITLE
Add CI to this repository

### ISSUE THREAD

**Issue by ph** [elastic/elastic-agent-client#6]
We should add CI to this repository to ensure:

- License
- Formatting
- Proto file is correctly build.
- Test passes

**Comment by ph** [comment]
@blakerouse Can work with @observablt-robots to add CI to this repository? I think we are missing a few mage tasks.

**Comment by kuisathaverat** [comment]
Is this the same(or related) that it is in https://github.com/elastic/beats/tree/master/x-pack/elastic-agent? it is to have more context.

**Comment by ph** [comment]
@kuisathaverat this repository will be a dependency of the elastic-agent and other beats.
I believe the CI would be similar to the package-registry task.

**Comment by kuisathaverat** [comment]
@ph Could you give us admin permissions on the repo for the team @elastic/observablt-robots?

**Comment by ph** [comment]
@kuisathaverat Done!

**Comment by ph** [comment]
When #7 is merged everything is addressed.

**Comment by ph** [comment]
closed by #7 and #8
