### ISSUE TITLE
Make it easier for callers of `unit.Expected()` to determine specific unit changes

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent-client#62]
See @fearful-symmetry's note here: https://github.com/elastic/elastic-agent-client/pull/56/files#r1119419360.

Today, callers of `unit.Expected()` must inspect the return value to figure out exactly which bits of the unit's configuration have actually changed.  We may want to provide callers an easier way to know about specific changes instead.

**Comment by cmacknz** [comment]
The addition of the change triggers was supposed to help this problem, unless I am missing something. @fearful-symmetry is there something else you had in mind for this?

**Comment by fearful-symmetry** [comment]
@cmacknz I think I made that original comment before I was aware of the change trigger thing--I'm not sure if it's been implemented yet?

**Comment by ycombinator** [comment]
>  think I made that original comment before I was aware of the change trigger thing

Ah, okay 😄 

> I'm not sure if it's been implemented yet?

Yes, it has.  See https://github.com/elastic/elastic-agent-client/blob/db7f3a085cc08dfa5056b18e1590172eb6e981b9/pkg/client/client_v2.go#L43-L60.

Okay to close this issue, then?

**Comment by jlind23** [comment]
Closing this based on @ycombinator comment above.
